
title: "IBM Capstone Project presentation"
email: topsecret@email.com
description: >- # this means to ignore newlines until "baseurl:"
  I just need this site to finish my IBM course!!
title: IBM Capstone Project Blog
email: mxxxxwxxxxxx@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This website is just here to finally finish my IBM Capstone Project.
baseurl: /ibm_capstone # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: -none-
github_username:  maruk101

# Build settings
theme: minima
plugins:
  - jekyll-feed
